### PR TITLE
Fix to work with laravel 5.5

### PR DESCRIPTION
**Pull request by adrianogl**

### CODE REVIEW

**Comment by hernandev** [comment]
Not sure what this PR does, can you help me figure it out?

Thanks

**Comment by hernandev** [comment]
@adrianogl Two PR's was actually opened to solve this issue.

The correct way of solving it is actually by having both methods and one should call the another, this way the package will be compatible with multiple Laravel versions.

Let'me know if you can include this so I can merge the request.

Otherwise, I'll do it myself and close this.

Thanks anyway.

**Comment by adrianogl** [comment]
Done ;)

**Comment by hernandev** [comment]
commits must enter on `develop` always.

Just noticed I can change that myself @flyingluscas

**Comment by hernandev** [comment]
gonna release this in a bit

**Pull request merged**
