### PR TITLE
composer: add package discovery for Laravel 5.5

### PR DESCRIPTION
**Pull request by flyingluscas**
Add support to [package discovery released on Laravel 5.5](https://laravel.com/docs/5.5/packages#package-discovery).

### CODE REVIEW

**Comment by hernandev** [comment]
Thanks for this feature @flyingluscas.

I'm not entirely in favor of this Laravel feature, in my opinion packages must be explicitly added instead of automatically to allow a little bit more control.

I'll put this on hold for a couple of days to test with this.

Thanks

**Comment by flyingluscas** [comment]
Sure @hernandev, I understand your point, but I think it also makes it easier to use the package, but I agree that it should be put on a balance to see if it's worth it :)

**Comment by hernandev** [comment]
@flyingluscas I have nothing against adding it, I'll just test for instructions on the readme also, that will need to reflect this.

Thanks, gonna merge it tonight

**Comment by flyingluscas** [comment]
Nice @hernandev, I can update the README in this PR too if you think is better.

**Comment by hernandev** [comment]
please!

**Comment by hernandev** [comment]
Also, ensure it works out of the box in a brand new laravel app. this way I can make the release ASAP

**Comment by flyingluscas** [comment]
@hernandev I've updated the README and tested the package with Laravel 5.5, it all seems to be working just fine :)

**Comment by hernandev** [comment]
Thanks man, that's awesome!

Gonna check it out and merge by morning, or as soon as I get some time here.

Thank you!

**Comment by hernandev** [comment]
Just one small problem @flyingluscas .

This is a **`GIT FLOW`** enabled repository, Pull Requests `MUST` go into develop. not master

**Comment by hernandev** [comment]
Sorry for not noticing the wrong branch before, if you cannot edit the PR and change the branch, try opening another pull request to the `develop` branch.

Thanks

**Comment by flyingluscas** [comment]
@hernandev no worries, I've changed the base branch and made a rebase with the `develop` branch, it looks okay to me, no conflicts :)

**Comment by hernandev** [comment]
Thanks, since it's a develop merge there's no problem to merge right away, gonna just do the testing before the releasing but I'm accepting it now.

Many thanks for this.

**Comment by flyingluscas** [comment]
Thanks @hernandev o/

**Pull request merged**
