### PR TITLE
composer: add test script to run phpunit

### PR DESCRIPTION
**Pull request by flyingluscas**
Add a script in the composer file to run all tests using just `composer test`.

### CODE REVIEW

**Comment by hernandev** [comment]
There are no actual tests on this package yet, so I'll put this on hold.

I'll close the PR since this is not your first / last contribution to this project, I will expect you to not take it personally.

It's just all test related things will be on hold until we decide what to do on the testing perspective.

Does that makes sense? Let's me know so I'll close this.

**Comment by flyingluscas** [comment]
Sure @hernandev, no worries, maybe I'll make another PR to create tests :)

**Comment by hernandev** [comment]
@flyingluscas thanks for this anyway, let's talk about it better in the next week so we can create a testing strategy for it

**Comment by flyingluscas** [comment]
Sure @hernandev, just let me know when :)

**Pull request closed without merging**
