### PR TITLE
[WIP] basic tests setup

### PR DESCRIPTION
**Pull request by mateusjatenee**

### CODE REVIEW

**Comment by hernandev** [comment]
That's great. please do not include not actual tests on it yet.

the class organization will change a little when I refactor some stuff, but please go ahead with the testing setup. It's looking great so far.

**Comment by mateusjatenee** [comment]
@hernandev perhaps the root namespace could be changed to `Codecasts\JWT`? `Codecasts\Auth\JWT\Auth` is kinda weird

**Comment by hernandev** [comment]
@mateusjatenee it's actually for a greater good, Codecasts is the root namespace on all our apps so calling it JWT makes it weird on our side.

**Comment by hernandev** [comment]
@mateusjatenee be free to include tests if you want. the changes I'll be doing will not affect tests too much. Thanks

**Pull request merged**
